# Generated by Django 5.0.7 on 2024-07-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='finished_at',
            field=models.DateField(),
        ),
    ]
