# Generated by Django 5.0.7 on 2024-07-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_alter_tarefa_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='finished_at',
            field=models.DateTimeField(),
        ),
    ]
